language: nix

sudo: false

env:
  global:
    - CACHIX_CACHE=dguibert
    - NUR_REPO=dguibert
    - secure: "KZZ4hxhXfz1ge2faZ86TGC5qT3lrnu3zudkAtGHydkQCiuWEH52Zm1s02cFfvh47C3A3Uxy1bFkwUlSxZMMQmn95/g+IMsM18XJgXT/pDR6CDrtQYDgsTtLKaepFZH1nPU0oXpHYcfQdbKZ/r177v3WCUwE2AnLeQ2vpg4bdT7B/dwyMNAAGUqd7ghAsDRt85n9yW4te+mDujw6oHwKOdV+wvG4o4sTtt7YXNGrB5rnZvPuDi95rJdHKLLRVETSSMDtinbzC5aaQKGB5DJEdek1CLDO+d7r6YhmRZnbVmKvHuTSlF1sXHYu3Cx5SvVwqzXIgfqxp7ghGOY56xl/cD0nDOqdE4HuT/Om84g7rwAXsgcGObn/5T2V6W78GurEnQjzYQqvmk1amcTDx01BBLeVcjFWk8dxp1mZ5JVrf+9ihLdXlOPzqlO8S1vLTxdff3ASMSlhH623U5fJsXMysRYfIrrgmoImHDKxdgMlIjlWIH4dJ4ps2Ym15VynuFGf3pHh9yDCFceGDniMB7tlkglCwqwGeLvMeg0hQYhQ+tg4/LusqHrRpTyr4TsrEICy1BHQqpduMVP8kET487XxzqIeB2dnCq7Ws9c0uV0wg44AVBuZL3lGfCCbICAREY4/jd7jBKGZf5TB517879IyQSIX2+1976LeVvly+Hl1Zpk8="

matrix:
  include:
    - env: NIX_PATH=nixpkgs=https://github.com/dguibert/nixpkgs/archive/pu.tar.gz

install:
 - nix-env -i nix
 - nix --version
 - if [ -n "${CACHIX_CACHE}" ]; then nix-env -iA cachix -f https://cachix.org/api/v1/install; fi
 - if [ -n "${CACHIX_CACHE}" ]; then cachix use "${CACHIX_CACHE}"; fi

script:
 - nix-build ci.nix -A buildOutputs
 - nix eval -f default.nix 'lib'
 - nix eval -f default.nix 'modules'
 - nix eval -f default.nix 'overlays'

after_success:
  - if [ -n "${CACHIX_CACHE}" ]; then nix-build ci.nix -A cacheOutputs | cachix push "${CACHIX_CACHE}"; fi
  - if [ "false" = "${TRAVIS_PULL_REQUEST}" -a "master" = "${TRAVIS_BRANCH}" ]; then
      curl -XPOST "https://nur-update.herokuapp.com/update?repo=${NUR_REPO}"; fi

