#!/usr/bin/env bash

git-is-merged () {
  merge_destination_branch=$1
  merge_source_branch=$2

  #git merge-base --is-ancestor $merge_source_branch $merge_destination_branch && echo "merged" || echo "not merged"
  git merge-base --is-ancestor $merge_source_branch $merge_destination_branch && return 0 || return 1
}

set -eux -o pipefail

git checkout master
nix flake lock --update-input nixpkgs --commit-lock-file
mr push

git checkout host/spartan
git-is-merged host/spartan master || git merge master
(
cd nixpkgs/spartan
nix run --no-write-lock-file .#nix -- nix flake lock --update-input upstream --commit-lock-file
)

git checkout host/levante || git checkout -b host/levante master
git-is-merged host/levante master || git merge master
(
cd nixpkgs/levante
nix run --no-write-lock-file .#nix -- nix flake lock --update-input upstream --commit-lock-file
)

git checkout host/lumi || git checkout -b host/lumi master
git-is-merged host/lumi master || git merge master
(
cd nixpkgs/lumi
nix run --no-write-lock-file .#nix -- nix flake lock --update-input upstream --commit-lock-file
)

git checkout host/default || git checkout -b host/default master
git-is-merged host/default master || git merge master
(
cd nixpkgs/default
nix run --no-write-lock-file .#nix -- nix flake lock --update-input upstream --commit-lock-file
)

git checkout master
